export const UPDATE_NAME = 'UPDATE_NAME';

export const UPDATE_AGE = 'UPDATE_AGE';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';

export const UPDATE_PASSWORD1 = 'UPDATE_PASSWORD1';

export const UPDATE_PASSWORD2 = 'UPDATE_PASSWORD2';

export const UPDATE_GENDER = 'UPDATE_GENDER';

export const UPDATE_TERMANDCONDITIONS = 'UPDATE_TERMANDCONDITIONS';

export const UPDATE_IMAGEUPLOAD = 'UPDATE_IMAGEUPLOAD';

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
